{
    'name': 'Localización de El Salvador - Facturación Electrónica (DTE)',
    'version': '19.0.1.16.0',
    'category': 'Accounting/Localizations',
    'summary': 'Facturación Electrónica DTE conforme a requerimientos del Ministerio de Hacienda de El Salvador',
    'author': 'DIAL Studio',
    'depends': ['base', 'account'],
    'data': [
        'data/res.country.state.csv',
        'data/l10n_sv.municipio.csv',
        'data/l10n_sv.actividad_economica.csv',
        'data/l10n_sv.tipo_establecimiento.csv',
        'data/l10n_sv.tributo.csv',
        'data/l10n_sv.condicion_operacion.csv',
        'data/l10n_sv.forma_pago.csv',
        'data/l10n_sv.tipo_documento.csv',
        'data/account_tax_data.xml',
        'data/ir_cron_data.xml',
        'views/l10n_sv_catalog_views.xml',
        'views/l10n_sv_dte_log_views.xml',
        'views/l10n_sv_dte_send_wizard_views.xml',
        'views/report_l10n_sv_dte_invoice.xml',
        'views/res_company_views.xml',
        'views/res_partner_views.xml',
        'views/account_move_views.xml',
        'security/ir.model.access.csv',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'test': [],
    'external_dependencies': {
        'python': ['requests', 'cryptography', 'qrcode'],
    },
}
