from . import res_company
from . import res_partner
from . import account_tax
from . import l10n_sv_municipio
from . import l10n_sv_actividad_economica
from . import l10n_sv_tipo_establecimiento
from . import l10n_sv_tributo
from . import l10n_sv_forma_pago
from . import l10n_sv_condicion_operacion
from . import l10n_sv_tipo_documento
from . import l10n_sv_api
from . import l10n_sv_signer
from . import l10n_sv_dte_log
from . import l10n_sv_dte_send_wizard
from . import account_move